# Generated by Django 3.1.2 on 2021-03-29 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirlineDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Airline', models.CharField(choices=[('1', 'INDIGO'), ('2', 'AIR INDIA'), ('3', 'GO AIR'), ('4', 'VISTARA')], max_length=2)),
                ('Flight_Num', models.CharField(max_length=7)),
                ('Terminal', models.CharField(max_length=2)),
                ('Departure_City', models.CharField(choices=[('1', 'New Delhi (DEL)'), ('2', 'Mumbai (BOM)'), ('3', 'Bangalore (BLR)'), ('4', 'Pune (PNQ)'), ('5', 'Chennai (MMA)'), ('6', 'Hyderabad (HYD)')], max_length=1)),
                ('Depart_Time', models.CharField(choices=[('1', '07:15'), ('2', '08:05'), ('3', '09:10'), ('4', '10:40'), ('5', '18:40'), ('6', '19:30'), ('7', '20:15'), ('8', '21:05')], max_length=2)),
                ('Arrival_City', models.CharField(choices=[('1', 'New Delhi (DEL)'), ('2', 'Mumbai (BOM)'), ('3', 'Bangalore (BLR)'), ('4', 'Pune (PNQ)'), ('5', 'Chennai (MMA)'), ('6', 'Hyderabad (HYD)')], max_length=2)),
                ('Arrival_Time', models.CharField(choices=[('1', '07:15'), ('2', '08:05'), ('3', '09:10'), ('4', '10:40'), ('5', '18:40'), ('6', '19:30'), ('7', '20:15'), ('8', '21:05')], max_length=2)),
                ('Ticket_Price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=11)),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.PositiveIntegerField()),
                ('Address', models.CharField(default=None, max_length=200)),
                ('Booktime', models.DateTimeField(auto_now_add=True)),
                ('Final_Fare', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Flight_Details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='airlinedetail', to='SwiftApp.airlinedetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
